services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    restart: always
    container_name: unifi-network-application
    volumes:
      - /data/unifi:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    ports:
      - 8443:8443       # Unifi web admin
      - 3478:3478/udp   # Unifi STUN
      - 10001:10001/udp # AP discovery
      - 8080:8080       # device communication
      - 1900:1900/udp   # optional (discoverable on L2)
      - 8843:8843       # optional (guest portal HTTPS redirect)
      - 8880:8880       # optional (guest portal HTTP redirect)
      - 6789:6789       # optional (mobile throughput test)
      # - 5514:5514/udp   # optional (remote syslog)
  unifi-db:
    image: docker.io/mongo:7.0
    restart: always
    container_name: unifi-db
    volumes:
      - /data/unifi-db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
